### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by seirdotexe** [ROBERT-MCDOWELL/almobine#1]
Hi there. Is there any way we can contact, like by mail? I have something interesting to show to you.

**Comment by ROBERT-MCDOWELL** [comment]
is it related to almobine? mathematics? physics?

**Comment by seirdotexe** [comment]
It's actually related to Flash, specifically AMF.

**Comment by ROBERT-MCDOWELL** [comment]
ha ok, but this is a topic I manage from other projects... I close this issue and send to you an email now
